"""empty message

Revision ID: 080f7a4f55d3
Revises: 
Create Date: 2019-09-02 22:10:24.023747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080f7a4f55d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('validate_token', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('access_token_expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('processed_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('input_quantity', sa.Integer(), server_default='3000', nullable=False),
    sa.Column('output_quantity', sa.Integer(), server_default='20', nullable=False),
    sa.ForeignKeyConstraint(['input_id'], ['raw_resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refined_commodities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('first_input_id', sa.Integer(), nullable=False),
    sa.Column('first_input_quantity', sa.Integer(), server_default='40', nullable=False),
    sa.Column('second_input_id', sa.Integer(), nullable=False),
    sa.Column('second_input_quantity', sa.Integer(), server_default='40', nullable=False),
    sa.Column('output_quantity', sa.Integer(), server_default='5', nullable=False),
    sa.ForeignKeyConstraint(['first_input_id'], ['processed_materials.id'], ),
    sa.ForeignKeyConstraint(['second_input_id'], ['processed_materials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('colonies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(), nullable=False),
    sa.Column('planet_name', sa.String(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('planet_type', sa.String(), nullable=False),
    sa.Column('planet_type_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colonies_processed_materials',
    sa.Column('processed_material_id', sa.Integer(), nullable=False),
    sa.Column('colony_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colony_id'], ['colonies.id'], ),
    sa.ForeignKeyConstraint(['processed_material_id'], ['processed_materials.id'], ),
    sa.PrimaryKeyConstraint('processed_material_id', 'colony_id')
    )
    op.create_table('colonies_raw_resources',
    sa.Column('raw_resource_id', sa.Integer(), nullable=False),
    sa.Column('colony_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colony_id'], ['colonies.id'], ),
    sa.ForeignKeyConstraint(['raw_resource_id'], ['raw_resources.id'], ),
    sa.PrimaryKeyConstraint('raw_resource_id', 'colony_id')
    )
    op.create_table('colonies_refined_commodities',
    sa.Column('refined_commodity_id', sa.Integer(), nullable=False),
    sa.Column('colony_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colony_id'], ['colonies.id'], ),
    sa.ForeignKeyConstraint(['refined_commodity_id'], ['refined_commodities.id'], ),
    sa.PrimaryKeyConstraint('refined_commodity_id', 'colony_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colonies_refined_commodities')
    op.drop_table('colonies_raw_resources')
    op.drop_table('colonies_processed_materials')
    op.drop_table('colonies')
    op.drop_table('refined_commodities')
    op.drop_table('characters')
    op.drop_table('processed_materials')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('raw_resources')
    # ### end Alembic commands ###
