"""empty message

Revision ID: 9f135f2eb76f
Revises: 080f7a4f55d3
Create Date: 2019-09-17 21:31:17.724610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f135f2eb76f'
down_revision = '080f7a4f55d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colonies', sa.Column('deleted', sa.Boolean(), server_default='FALSE', nullable=True))
    op.add_column('colonies_processed_materials', sa.Column('deleted', sa.Boolean(), server_default='FALSE', nullable=True))
    op.add_column('colonies_raw_resources', sa.Column('deleted', sa.Boolean(), server_default='FALSE', nullable=True))
    op.add_column('colonies_refined_commodities', sa.Column('deleted', sa.Boolean(), server_default='FALSE', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colonies_refined_commodities', 'deleted')
    op.drop_column('colonies_raw_resources', 'deleted')
    op.drop_column('colonies_processed_materials', 'deleted')
    op.drop_column('colonies', 'deleted')
    # ### end Alembic commands ###
