INSERT INTO public.raw_resources (type_id, name) VALUES (2268, 'Aqueous Liquids');
INSERT INTO public.raw_resources (type_id, name) VALUES (2305, 'Autotrophs');
INSERT INTO public.raw_resources (type_id, name) VALUES (2267, 'Base Metals');
INSERT INTO public.raw_resources (type_id, name) VALUES (2288, 'Carbon Compounds');
INSERT INTO public.raw_resources (type_id, name) VALUES (2287, 'Complex Organisms');
INSERT INTO public.raw_resources (type_id, name) VALUES (2307, 'Felsic Magma');
INSERT INTO public.raw_resources (type_id, name) VALUES (2272, 'Heavy Metals');
INSERT INTO public.raw_resources (type_id, name) VALUES (2309, 'Ionic Solutions');
INSERT INTO public.raw_resources (type_id, name) VALUES (2073, 'Microorganisms');
INSERT INTO public.raw_resources (type_id, name) VALUES (2310, 'Noble Gas');
INSERT INTO public.raw_resources (type_id, name) VALUES (2270, 'Noble Metals');
INSERT INTO public.raw_resources (type_id, name) VALUES (2306, 'Non-CS Crystals');
INSERT INTO public.raw_resources (type_id, name) VALUES (2286, 'Planktic Colonies');
INSERT INTO public.raw_resources (type_id, name) VALUES (2311, 'Reactive Gas');
INSERT INTO public.raw_resources (type_id, name) VALUES (2308, 'Suspended Plasma');