INSERT INTO public.raw_resources (name) VALUES ('Aqueous Liquids');
INSERT INTO public.raw_resources (name) VALUES ('Autotrophs');
INSERT INTO public.raw_resources (name) VALUES ('Base Metals');
INSERT INTO public.raw_resources (name) VALUES ('Carbon Compounds');
INSERT INTO public.raw_resources (name) VALUES ('Complex Organisms');
INSERT INTO public.raw_resources (name) VALUES ('Felsic Magma');
INSERT INTO public.raw_resources (name) VALUES ('Heavy Metals');
INSERT INTO public.raw_resources (name) VALUES ('Ionic Solutions');
INSERT INTO public.raw_resources (name) VALUES ('Micro Organisms');
INSERT INTO public.raw_resources (name) VALUES ('Noble Gas');
INSERT INTO public.raw_resources (name) VALUES ('Noble Metals');
INSERT INTO public.raw_resources (name) VALUES ('Non-CS Crystals');
INSERT INTO public.raw_resources (name) VALUES ('Planktic Colonies');
INSERT INTO public.raw_resources (name) VALUES ('Reactive Gas');
INSERT INTO public.raw_resources (name) VALUES ('Suspended Plasma');
