INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (2393, 'Bacteria', 9, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (2396, 'Biofuels', 4, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (3779, 'Biomass', 13, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (2401, 'Chiral Structures', 12, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (2390, 'Electrolytes', 8, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (2397, 'Industrial Fibers', 2, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (2392, 'Oxidizing Compound', 14, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (3683, 'Oxygen', 10, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (2389, 'Plasmoids', 15, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (2399, 'Precious Metals', 11, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (2395, 'Proteins', 5, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (2398, 'Reactive Metals', 3, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (9828, 'Silicon', 6, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (2400, 'Toxic Metals', 7, 3000, 20);
INSERT INTO public.processed_materials (type_id, name, input_id, input_quantity, output_quantity) VALUES (3645, 'Water', 1, 3000, 20);