INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Biocells', 10, 2);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Construction Blocks', 14, 12);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Consumer Electronics', 4, 14);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Coolant', 15, 5);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Enriched Uranium', 14, 10);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Fertilizer', 11, 1);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Genetically Enhanced Livestock', 3, 11);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Livestock', 2, 11);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Mechanical Parts', 10, 12);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Microfiber Shielding', 13, 6);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Miniature Electronics', 13, 4);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Nanites', 12, 1);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Oxides', 8, 7);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Polyaramids', 6, 7);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Polytextiles', 6, 2);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Rocket Fuel', 5, 9);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Silicate Glass', 13, 7);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Superconductors', 15, 9);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Supertensile Plastics', 3, 8);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Synthetic Oil', 8, 5);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Test Cultures', 15, 1);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Transmitter', 4, 9);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Viral Agent', 3, 1);
INSERT INTO public.refined_commodities (name, first_input_id, second_input_id) VALUES ('Water-Cooled CPU', 15, 12);

alter sequence refined_commodities_id_seq restart with 24;